### ISSUE TITLE
No configuration for LRO to generate only GAPIC, without proto

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#212]
### What

For Ruby LRO, we want artman to generate only the GAPIC files before it creates a PR to gax-ruby. https://github.com/googleapis/gax-ruby/pull/72/files is incorrect because it contains compiled proto classes as well. This does not appear to be possible with the GitHub publish via the existing configuration parameters, since for LRO the GAPIC and proto files live in the same directory. (Please correct me if I'm wrong, though!)

### To reproduce

`$ artman --api longrunning --lang ruby --publish github --target gax`

### Why

For LRO, the protos will be contained in the common proto package, not GAX.

cc @landrito @eoogbe

**Comment by lukesneeringer** [comment]
> since for LRO the GAPIC and proto files live in the same directory. (Please correct me if I'm wrong, though!)

Even though the `paths` normally references directories, it _can_ reference files. If the number of files is small, that could be a solution.

In general, I like the fact that the `GapicClientPipeline` runs the `GrpcClientPipeline` also, since in essentially every other case, this is what you want. If using `paths` is not feasible, however, it would be reasonable to shift the pipelines around.

Essentially I would change `GapicClientPipeline` back to being GAPIC only and make a `EverythingPipeline` (named something better than that) that does both, and then change the default to the new one.

But if LRO is really the only case, maybe see if `paths` is an acceptable solution first?

**Comment by ethanbao** [comment]
The new GAPIC_ONLY artifact type will only generate GAPIC layer.
