### ISSUE TITLE
Standardize the artman exit codes

### ISSUE THREAD

**Issue by ethanbao** [googleapis/artman#368]
Currently, it return 32/64/96 for no clear reason/definition.

**Comment by lukesneeringer** [comment]
I used exit code 64 to be a CLI usage error, in accordance with `sysexits.h`. (This is far from a universal standard, but seemed like a good idea at the time.)

I do not much care what the exit codes are but I _do_ care that the various exit codes are distinct, because ultimate users might have a reason to detect and allow particular non-zero exit codes in some edge case situations.
