### ISSUE TITLE
Support artman config without REPOROOT

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#51]
REPOROOT causes confusion when running artman in remote mode -- on the local machine, it corresponds to a directory that contains both the real googleapis repo and a "local_repo", whereas remotely it refers to a single directory named "googleapis" that corresponds to the merged value of both of these.

The artman config refers only to the remote setup; a path such as `{REPOROOT}/googleapis/foo/bar.py` may refer locally either to `googleapis/foo/bar.py` or to `{LOCAL_REPO}/foo/bar.py`. This is particularly confusing because the `googelapis` in the `{REPOROOT}/googleapis/foo/bar.py` may not exist on the local path if the file refered to is actually `{LOCAL_REPO}/foo/bar.py`.

Instead, we could support relative paths in the artman config, like `foo/bar.py`. This does not to reference googleapis, and so solves the issue of having invalid paths in the config on the local machine.

**Comment by lukesneeringer** [comment]
I took a different pass at this with `local_paths`, which allows each repository to _either_ be derived from `reporoot` _or_ explicitly defined. I assert it probably solves for this problem.

Note that in the remote pipeline, we will just check out the applicable repos. I think that is orthogonal to this issue, though.

**Comment by geigerj** [comment]
@lukesneeringer For context, this issue was originally raised by some of our users who were running the remote pipeline with protos that were not yet checked into the applicable repos; we supported a phase in which the users specified a local directory that was then uploaded and merged into a clone of the `googleapis` repo. This caused quite a lot of confusion from our users about what files were coming from where.

**Comment by lukesneeringer** [comment]
I see. My changes do not really make _that_ particular problem much better (although they certainly do not make it any _worse_). Really the issue is not with `reporoot`, it is with `googleapis`.

The ultimate solution to _this_ problem is probably to infer basically everything that is not in the artman or GAPIC YAML files; we do not really need to outright specify `lang/common.yaml` every time; it would be entirely okay to simply make everything in that file settings that _can_ be specified in a user YAML but which have these defaults otherwise.

This clearly needs more design work. Leaving this issue in place.

**Comment by ethanbao** [comment]
This is no longer required under new artman syntax.
