### ISSUE TITLE
Beta APIs should be marked beta, not alpha

### ISSUE THREAD

**Issue by jadekler** [googleapis/artman#534]
See: https://godoc.org/cloud.google.com/go/cloudtasks/apiv2beta3, which has a note `NOTE: This package is in alpha.`.

This ends up being important, because our narrative for whether customers should use a package includes considerations about whether it's alpha or beta.

**Comment by andreamlin** [comment]
@jadekler Would you mind providing an example or two in the wild?

**Comment by jadekler** [comment]
@andreamlin PTAL the one linked above :) https://godoc.org/cloud.google.com/go/cloudtasks/apiv2beta3

Lmk if you'd like another and I can see if I can dig one up!

**Comment by andreamlin** [comment]
@jadekler ahh I was so used to seeing clients on github I didn't realize that that was a generated Go client.

For the Go generated docs, the release level comes from the language settings in the gapic yaml. 
See https://github.com/googleapis/gapic-generator/pull/2460 for an example for how to set the `release_level` config and the resulting change in the generated doc.

If a gapic config doesn't specify the release level, then the go gapic generation defaults to saying it's in Alpha status. (This might be an issue for later?)

Would the yoshi-go team be able to mark all the beta APIs in google3 in the Go language settings on the gapic configs?

**Comment by jadekler** [comment]
@andreamlin Could that be made a required field? (or is that outside y'alls control?)

Alternatively, can the fallback be to look for alpha|beta in the path?

**Comment by andreamlin** [comment]
We could make it a required field, though that enforcing that would probably break most APIs for some of their languages, since not every language x API combo has the release version specified. I do agree that enforcing release version per client would be most ideal.

re falling back: I think the issue is that the API version is an upper bound for the client version, so an API can be GA or Beta while its generated client is still Beta or Alpha.

I don't think a computer has enough context to figure out what version a generated client is; even I don't know when we can push a client to Beta or GA?? Age and stability of the surface are some of the biggest factors of what version a client should be released at, and that's kinda up to us to decide.

**Comment by andreamlin** [comment]
@michaelbausor can you sanity check me on this?

**Comment by jadekler** [comment]
@andreamlin Could we make it a required field in the same CL as adding that field to all protos?

Also, I _believe_ all gapics are of the form `apivXalphaY`, `apivXbetaY`, and `apivX`, so I think we should be able to infer alpha/beta? I might be missing something though!

**Comment by michaelbausor** [comment]
@andreamlin is right re the generator not having enough context. There may exist an alpha client library for a vX or vXbetaY service, because it is a new client library / doesn't have samples etc. And we *definitely* do not want the generator to accidentally describe the client library as having greater stability than it actually does.

Re making it required - it could be done in one big CL. I'm not sure of the scope - how many are missing this field? Is it only Go that this affects?

**Comment by jadekler** [comment]
Right, I had only intended for it to guess at alpha|beta, not stable.

Btw - I'm willing to help make that universal-required-field-set change happen if y'all can give me a hand on making it required?

**Comment by andreamlin** [comment]
I think it wouldn't be too hard to make it required. The check would most easily be enforced when generating the Go client, and that should only be a couple lines.

If that's an ok place to enforce the versioning for Go clients specifically, then sure I can help out there.

**Comment by jadekler** [comment]
SG - sent you a calendar invite.

**Comment by jadekler** [comment]
Decision from meeting with Andrea: if the package name contains `beta`, the version is inferred to be `beta` and documentation is accordingly symmetrical.
